apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: {{CERTIFICATE_AUTHORITY_DATA}}
    server: {{SERVER_URL}}
  name: cluster
contexts:
- context:
    cluster: cluster
    namespace: {{NAMESPACE}}
    user: admin
  name: only-context
current-context: only-context
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: {{USER_TOKEN}}